---
title: "Mapas por CCAA y provincias"
description: |
  Los paquetes basicos.
author:
  - name: Molly Sheep 
    url: https://example.com/norajones
    affiliation: KSNET
    affiliation_url: https://ksnet.eu
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE)

library(tidyverse)
#library(palmerpenguins)
library(hrbrthemes)
library(viridis)

```

Bienvenido a nuestro analisis de los pinguinos espanyoles. Empezaremos con un breve resumen de lo que contiene nuestra base de datos.


```{r}

#install.packages("mapSpain", dependencies = TRUE)

library(mapSpain)


```

## Comunidades autónomas

```{r}

census <- mapSpain::pobmun19

# Extract CCAA from base dataset

codelist <- mapSpain::esp_codelist


census <- census %>%
  left_join(select(codelist, cpro, ccaa.shortname.es), by = c("cpro"))


# Summarize by CCAA
census_ccaa <- census %>%
  rename(ccaa = ccaa.shortname.es) %>%
  group_by(ccaa) %>%
  summarize(total_men = sum(men),
            total_women = sum(women),
            total = sum(pob19)) %>%
  mutate(share_women = round(100*total_women / total, 2))

# Merge into spatial data

CCAA_sf <- esp_get_ccaa() %>%
  rename(ccaa = ccaa.shortname.es)
CCAA_sf <- left_join(CCAA_sf, census_ccaa)
can <- esp_get_can_box()



```


Para verificar que la aleatorizacion se hizo bien, podemos hacer una balance table:

```{r}

ggplot(CCAA_sf) +
  geom_sf(aes(fill = share_women),
    color = "grey70",
    lwd = .3
  ) +
  geom_sf(data = can, color = "grey70") +
  geom_sf_label(aes(label = share_women),
    fill = "white", alpha = 0.5,
    size = 3,
    label.size = 0
  ) +
  scale_fill_gradientn(
    colors = hcl.colors(10, "Blues", rev = TRUE),
    n.breaks = 10,
    labels = function(x) {
      sprintf("%1.1f%%", x)
    },
    guide = guide_legend(title = "Porc. women")
  ) +
  theme_void() +
  theme(legend.position = c(0.1, 0.6))



```


## Provincias

```{r}


# Summarize by CCAA
census_prov <- census %>%
  group_by(cpro) %>%
  summarize(total_men = sum(men),
            total_women = sum(women),
            total = sum(pob19)) %>%
  mutate(share_women = round(100*total_women / total, 2))

# Merge into spatial data

prov_sf <- esp_get_prov() 
prov_sf <- left_join(prov_sf, census_prov)
can <- esp_get_can_provinces()



```


```{r}
#prov_sf <- esp_get_prov()


ggplot(prov_sf) +
  geom_sf(aes(fill = share_women),
    color = "grey70",
    lwd = .3
  ) +
  geom_sf(data = can, color = "grey70") +
  geom_sf_label(aes(label = share_women),
    fill = "white", alpha = 0.5,
    size = 3,
    label.size = 0
  ) +
  scale_fill_gradientn(
    colors = hcl.colors(10, "Blues", rev = TRUE),
    n.breaks = 10,
    labels = function(x) {
      sprintf("%1.1f%%", x)
    },
    guide = guide_legend(title = "Porc. women")
  ) +
  theme_void() +
  theme(legend.position = c(0.1, 0.6))

```

## Provincias animadas

```{r eval=FALSE, echo=TRUE}

library(ggiraph)

p <- prov_sf %>%
  mutate(id = row_number(),
         tooltip = paste("La provincia de ", ine.prov.name, "tiene un", share_women, "% de mujeres")) %>% 
  ggplot() +
  geom_sf_interactive(aes(fill = share_women, tooltip = tooltip, data_id = id),
    color = "grey70",
    lwd = .3
  ) +
  geom_sf(data = can, color = "grey70") +
  geom_sf_label(aes(label = share_women),
    fill = "white", alpha = 0.5,
    size = 3,
    label.size = 0
  ) +
  scale_fill_gradientn(
    colors = hcl.colors(10, "Blues", rev = TRUE),
    n.breaks = 10,
    labels = function(x) {
      sprintf("%1.1f%%", x)
    },
    guide = guide_legend(title = "Porc. women")
  ) +
  theme_void() +
  theme(legend.position = c(0.1, 0.6))

girafe(code = print(p), width_svg = 13, height_svg = 6)


```


```



